apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "explorer.fullname" . }}
  labels:
    {{- include "explorer.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.app.environment | quote }}
  API_HOST: {{ .Values.app.apiUrl | quote }}
  GRAPHQL_HOST: {{ .Values.app.graphqlUrl | quote }}
  FAUCET_ROOT_URL: {{ .Values.app.faucetUrl | quote }}