version: 2.1

orbs:
  docker: circleci/docker@1.7.0

parameters:
  ui-package-modified:
    type: boolean
    default: false
  run-community-site-service-workflow:
    type: boolean
    default: false

aliases:
  - &build_config
    docker:
      - image: alpine:3.14
  - &step_setup_remote_docker
    setup_remote_docker:
      version: 19.03.14
      docker_layer_caching: true

jobs:
  build-community-site:
    <<: *build_config
    steps:
      - checkout
      - *step_setup_remote_docker
      - run:
          name: Build image
          shell: /bin/bash -eo pipefail
          command: |
            docker build -t taraxa-community-site:latest -f services/community-site/Dockerfile .

workflows:
  community-site:
    when:
      or:
        - << pipeline.parameters.run-community-site-service-workflow >>
        - << pipeline.parameters.ui-package-modified >>
    jobs:
      - build-community-site