app:
  environment: qa
  claimContractAddress: '0x780AAd8C6C4973E57cB9399bd167118386E72EcB'
  provider: 'https://ropsten.infura.io/v3/1c60d8f404244a1fbafdd6131f01f9d2'

  dbHost: 10.39.113.3

image:
  repository: gcr.io/jovial-meridian-249123/taraxa-claim-api-develop

nodeSelector:
  cloud.google.com/gke-nodepool: taraxa-community-qa

ingress:
  enabled: true
  hosts:
    - host: api.qa.claim.taraxa.io
  tls:
    - secretName: wild-qa-claim-taraxa-io-tls
      hosts:
        - api.qa.claim.taraxa.io
