apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "community-delegation.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.app.serverPort | quote }}
  DATABASE_HOST: {{ .Values.app.dbHost | quote }}
  DATABASE_PORT: {{ .Values.app.dbPort | quote }}
  DATABASE_NAME: {{ .Values.app.dbName | quote }}
  STAKING_CONTRACT_ADDRESS: {{ .Values.app.stakingContractAddress | quote }}
  MAINNET_ENDPOINT: {{ .Values.app.mainnetEndpoint | quote }}
  NODE_ENV: {{ .Values.app.environment | quote }}
