{{- $secret := (lookup "v1" "Secret" .Release.Namespace .Release.Name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "community-delegation.labels" . | nindent 4 }}
type: Opaque
data:
{{ if $secret }}
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{ else }}
  DATABASE_USER: {{ .Values.app.secrets.dbUser | b64enc | quote }}
  DATABASE_PASS: {{ .Values.app.secrets.dbPass | b64enc | quote }}
  QUEUE_PASS: {{ .Values.app.secrets.queuePass | b64enc | quote }}
  JWT_SECRET: {{ .Values.app.secrets.jwtSecret | b64enc | quote }}
  ETHEREUM_ENDPOINT: {{ .Values.app.secrets.ethereumEndpoint | b64enc | quote }}
  MAINNET_WALLET: {{ .Values.app.secrets.mainnetWallet | b64enc | quote }}
  TESTNET_WALLET: {{ .Values.app.secrets.testnetWallet | b64enc | quote }}
{{- end }}